kind: pipeline
type: docker
name: default


steps:
- name: build
  image: node
  commands:
    - npm install
    - npm run buildPro
    - cp -r -f ./build  /target/
    - cp -r -f ./Dockerfile /target/
    - cp -r -f ./nginx.conf /target/
  volumes:
  - name: nodemodules
    path: /drone/src/node_modules
  - name: target
    path: /target

- name: gitcommit
  image: alpine/git
  volumes:
    - name: target
      path: /target
  commands:
    - git rev-parse --short HEAD > commit.log
    - cp -f ./commit.log /target/commit.log

- name: dockerbuild
  image: docker
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
    - name: dockervarlib
      path: /var/lib/docker
    - name: target
      path: /target
  commands:
    - cd /target
    - docker build -t lurise/teafrontend:$(head -n 1 commit.log) .
    - docker login -u lurise -p 8263213a
    - docker push lurise/teafrontend:$(head -n 1 commit.log)
- name: edityml
  image: lurise/yedit:v0.1
  volumes:
    - name: dockercomposeYmlDir
      path: /app/docker-compose.yml
    - name: target
      path: /target
  commands:
    - cp ./commit.log /target/
    - cd /app
    - ./yedit --service=teafrontend --imagename=lurise/teafrontend:$(head -n 1 /target/commit.log)
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 122.114.0.26
    username: root
    password:
      from_secret: ssh_passwod
    port: 22000
    script:
      - cd /home/data
      - docker-compose up -d


volumes:
  - name: nodemodules
    host:
      path: /home/data/drone/teachat/frontend/node_modules
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: dockervarlib
    host:
      path: /var/lib/docker
  - name: target
    host:
      path: /home/data/drone/teachat/frontend/target
  - name: dockercomposeYmlDir
    host:
      path: /home/data/docker-compose.yml
